name: itopw-front

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Docker daemon for insecure Harbor registry and systemd cgroup
        run: |
          echo '{
            "insecure-registries": ["${{ secrets.HARBOR_URL }}"],
            "exec-opts": ["native.cgroupdriver=systemd"]
          }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Set up Docker Buildx with valid cgroup-parent
        run: |
          docker buildx create --name mybuilder --use \
            --driver-opt network=host \
            --buildkitd-flags '--oci-worker-caps=all --oci-worker-cgroup-parent=/docker.slice'
          docker buildx inspect mybuilder --bootstrap

      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.HARBOR_URL }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.HARBOR_URL }}/itopw/itopw-front:${{ env.NEW_TAG }}
          outputs: type=image,push=true
          insecure: true
          builder: mybuilder
      
      - name: Checkout Kustomize repository
        uses: actions/checkout@v3
        with:
          repository: DBFIS-LifeInsuranceInfraTeam/manifest
          ref: main
          token: ${{ secrets.PAT }}
          path: manifest

      - name: Update Kubernetes resources with new image
        run: |
          cd manifest/front
          kustomize edit set image ${{ secrets.HARBOR_URL }}/itopw/itopw-front:${{ env.NEW_TAG }}
          cat kustomization.yaml

      - name: Commit and push manifest changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          cd manifest
          git config --global user.email "gb.lee@dbinc.co.kr"
          git config --global user.name "gblee-dbinc"
          git commit -am "Update image tag to ${{ env.NEW_TAG }}"
          git push -u origin main
