name: itopw-front

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx with insecure registry
        run: |
          docker buildx create --name mybuilder --use
          docker buildx inspect mybuilder --bootstrap
          echo '{"insecure-registries": ["${{ secrets.HARBOR_URL }}"]}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
          
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.PAT }}

      - name: Set new tag and changelog as environment variables
        run: |
          TAG_VERSION="${{ steps.tag_version.outputs.new_tag }}"
          CLEAN_TAG=$(echo $TAG_VERSION | sed 's/refs-tags-//g')
          echo "NEW_TAG=$CLEAN_TAG" >> $GITHUB_ENV

      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ env.NEW_TAG }}
          release_name: Release ${{ env.NEW_TAG }}
          body: ${{ env.CHANGELOG }}

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ secrets.HARBOR_URL }}/itopw/itopw-front
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.HARBOR_URL }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.HARBOR_URL }}/itopw/itopw-front:${{ env.NEW_TAG }}
          outputs: type=image,push=true
          insecure: true
          builder: mybuilder
      
      - name: Checkout Kustomize repository
        uses: actions/checkout@v3
        with:
          repository: DBFIS-LifeInsuranceInfraTeam/manifest
          ref: main
          token: ${{ secrets.PAT }}
          path: manifest

      - name: Update Kubernetes resources with new image
        run: |
          cd manifest/front
          kustomize edit set image ${{ secrets.HARBOR_URL }}/itopw/itopw-front:${{ env.NEW_TAG }}
          cat kustomization.yaml

      - name: Commit and push manifest changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          cd manifest
          git config --global user.email "gb.lee@dbinc.co.kr"
          git config --global user.name "gblee-dbinc"
          git commit -am "Update image tag to ${{ env.NEW_TAG }}"
          git push -u origin main
