name: itopw-front

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_INSECURE: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.PAT }}

      - name: Set new tag and changelog as environment variables
        run: |
          TAG_VERSION="${{ steps.tag_version.outputs.new_tag }}"
          CLEAN_TAG=$(echo $TAG_VERSION | sed 's/refs-tags-//g')
          echo "NEW_TAG=$CLEAN_TAG" >> $GITHUB_ENV

      - name: Configure Docker daemon
        run: |
          echo '{
            "insecure-registries": ["${{ secrets.HARBOR_URL }}"],
            "exec-opts": ["native.cgroupdriver=systemd"]
          }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Set up Docker Buildx
        run: |
          docker buildx create --name mybuilder --use --driver-opt network=host
          docker buildx inspect mybuilder --bootstrap
          echo '{"registry-mirrors": ["http://<HARBOR_URL>"], "insecure-registries": ["${{ secrets.HARBOR_URL }}"]}' | sudo tee /etc/buildkit/buildkitd.toml
          sudo systemctl restart docker

      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.HARBOR_URL }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
          insecure: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.HARBOR_URL }}/itopw/itopw-front:${{ env.NEW_TAG }}
          outputs: type=image,push=true
          builder: mybuilder
          build-args:
            - BUILDKIT_INLINE_CACHE=1
        env:
          DOCKER_CLI_FLAGS: "--insecure-registry ${{ secrets.HARBOR_URL }}"
      
      - name: Checkout Kustomize repository
        uses: actions/checkout@v3
        with:
          repository: DBFIS-LifeInsuranceInfraTeam/manifest
          ref: main
          token: ${{ secrets.PAT }}
          path: manifest

      - name: Update Kubernetes resources with new image
        run: |
          cd manifest/front
          kustomize edit set image ${{ secrets.HARBOR_URL }}/itopw/itopw-front:${{ env.NEW_TAG }}
          cat kustomization.yaml

      - name: Commit and push manifest changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          cd manifest
          git config --global user.email "gb.lee@dbinc.co.kr"
          git config --global user.name "gblee-dbinc"
          git commit -am "Update image tag to ${{ env.NEW_TAG }}"
          git push -u origin main
